// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SabalanTracking.Data;

#nullable disable

namespace SabalanTracking.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20231024020203_initial1")]
    partial class initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SabalanTracking.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6668d620-7fce-4783-901d-0d59994bcd2d"),
                            Description = " ",
                            Name = "دستگاه جوش التراسونیک"
                        },
                        new
                        {
                            Id = new Guid("35ede537-b968-44d4-bb00-6f817e6d0c5c"),
                            Description = " ",
                            Name = "دستگاه برش التراسونیک پارچه"
                        },
                        new
                        {
                            Id = new Guid("003fc3e0-8a0c-40aa-8a4d-b037267ebaea"),
                            Description = " ",
                            Name = "دستگاه تزریق شماره 1"
                        },
                        new
                        {
                            Id = new Guid("7954f335-9e55-4cdc-b3d3-2097bc6dafb3"),
                            Description = " ",
                            Name = "دستگاه تزریق شماره 2"
                        },
                        new
                        {
                            Id = new Guid("9fc05371-9b98-4b8e-9302-1518290148b6"),
                            Description = " ",
                            Name = "دستگاه تزریق شماره 3"
                        },
                        new
                        {
                            Id = new Guid("2761a3a4-9e8b-4b10-8812-69314cce08ee"),
                            Description = " ",
                            Name = "دستگاه تزریق شماره 4"
                        },
                        new
                        {
                            Id = new Guid("da5d78d5-02ec-4186-a708-fdaa8b591d27"),
                            Description = " ",
                            Name = "دستگاه تزریق شماره عباسی"
                        },
                        new
                        {
                            Id = new Guid("75267e76-9f8b-4a21-ad3f-a05a34ff2772"),
                            Description = " ",
                            Name = "دستگاه سیلر بسته بندی"
                        });
                });

            modelBuilder.Entity("SabalanTracking.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Materials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("47c6036e-4a5a-4687-a6f5-d1b1737ed94f"),
                            CatId = new Guid("5efae653-911d-40c9-aaa5-666135fe4a85"),
                            Name = "فیلتر HME",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("d2f83526-bf87-4e47-b29f-af82d0eb4bdb"),
                            CatId = new Guid("5efae653-911d-40c9-aaa5-666135fe4a85"),
                            Name = "فیلتر VFE",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("f35d2712-0808-48e8-b8df-c22067a6676f"),
                            CatId = new Guid("5efae653-911d-40c9-aaa5-666135fe4a85"),
                            Name = "فیلتر اسپیرومتری",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("44f3b369-cc54-418f-a16a-ea936cbb4ac8"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "فیلتر ویپک HME",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("75879f56-0c43-4de8-afc3-f05026e260b9"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "ویپک VFE",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("b155638c-1d73-4cbf-ab11-738fe5ab1770"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "ویپک اسپیرومتری",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("ff06ec45-4aec-4006-b114-0739a804ba01"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "بدنه فیلتر HME بدون درپوش",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("aff6c1d9-4834-4588-a835-14a683e502a8"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "بدنه فیلتر HME با درپوش",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("869784d8-b821-4e82-bef4-d8a924bfbe33"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "درپوش",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("2022077b-a281-4f92-a9b1-6e484dd10673"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "بدنه فیلتر آنتی باکتریال با درپوش",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("c9e6ef94-7c35-4135-b947-6e61fe50cad9"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "بدنه فیلتر آنتی باکتریال بدون درپوش",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("501ad51a-742b-4728-ad77-c122f1c25471"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "بدنه فیلتر اسپیرومتری شماره 1",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("91369451-9d26-4fa3-a182-143dea3062c8"),
                            CatId = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Name = "بدنه فیلتر اسپیرومتری شماره 2",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("f3828063-762a-4c1d-ba90-c4b33b945b6b"),
                            CatId = new Guid("868ecb86-545f-413c-91b4-e15a73f99ddc"),
                            Name = "پلی استایرن-PS",
                            Unit = "کیلوگرم"
                        },
                        new
                        {
                            Id = new Guid("437ee4fe-2fe4-4f8c-ae5d-2d41e7fd80a0"),
                            CatId = new Guid("868ecb86-545f-413c-91b4-e15a73f99ddc"),
                            Name = "پلی پروپیلن-PP",
                            Unit = "کیلوگرم"
                        },
                        new
                        {
                            Id = new Guid("5c41e3c0-7ddc-4f63-92a4-dacab5d32bd6"),
                            CatId = new Guid("868ecb86-545f-413c-91b4-e15a73f99ddc"),
                            Name = "PVC",
                            Unit = "کیلوگرم"
                        },
                        new
                        {
                            Id = new Guid("e667e9c0-7811-4cef-b935-965fb434c9b4"),
                            CatId = new Guid("868ecb86-545f-413c-91b4-e15a73f99ddc"),
                            Name = "کاغذ جاذب رطوبت",
                            Unit = "عدد"
                        },
                        new
                        {
                            Id = new Guid("c1d74061-62e4-4b88-9284-c7a574126aeb"),
                            CatId = new Guid("868ecb86-545f-413c-91b4-e15a73f99ddc"),
                            Name = "ملت بلون",
                            Unit = "کیلوگرم"
                        },
                        new
                        {
                            Id = new Guid("56d4f7fe-acad-44f5-8313-0b536505537c"),
                            CatId = new Guid("868ecb86-545f-413c-91b4-e15a73f99ddc"),
                            Name = "اسپان باند",
                            Unit = "کیلوگرم"
                        });
                });

            modelBuilder.Entity("SabalanTracking.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b50fea1-cce1-43f4-a5f3-f141f1367505"),
                            Name = "عباسی"
                        },
                        new
                        {
                            Id = new Guid("42c5e395-a784-4975-86b8-af29ae4220ed"),
                            Name = "پژمان"
                        },
                        new
                        {
                            Id = new Guid("7b2081cb-ccc6-4d81-95b3-c01c5b4d359e"),
                            Name = "مهندس عبدالله پور"
                        },
                        new
                        {
                            Id = new Guid("be7d08c4-d227-4a6e-8a9d-234ad6bc62a9"),
                            Name = "مسعود"
                        },
                        new
                        {
                            Id = new Guid("55bb7053-f2b4-405c-9b5c-8ecb4ede0f22"),
                            Name = "رضا"
                        },
                        new
                        {
                            Id = new Guid("becbfd78-bc37-419d-a12b-1e4f3f3a46bb"),
                            Name = "اپراتور 1 عباسی"
                        },
                        new
                        {
                            Id = new Guid("f0e199f6-7d67-4111-89cf-bcd57029bfc4"),
                            Name = "اپراتور 2 عبداللهی"
                        });
                });

            modelBuilder.Entity("SabalanTracking.Models.Proces", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProcessNameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProcessNameId");

                    b.ToTable("Processes", (string)null);
                });

            modelBuilder.Entity("SabalanTracking.Models.ProcessDetaile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QntyPerPc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessDetails", (string)null);
                });

            modelBuilder.Entity("SabalanTracking.Models.ProcessName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProcessNames", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8233d591-21c3-4b86-9725-ae84ad56a191"),
                            Name = "برش پارچه"
                        },
                        new
                        {
                            Id = new Guid("aed762ea-c4ca-4dcb-9429-f50096ae589f"),
                            Name = "تزریق پلاستیک"
                        },
                        new
                        {
                            Id = new Guid("22e4e3ef-523b-4582-9531-09da5daa2cf5"),
                            Name = "جوش التراسونیک"
                        },
                        new
                        {
                            Id = new Guid("deed5511-831f-4943-bb34-554844d81430"),
                            Name = "بسته بندی"
                        },
                        new
                        {
                            Id = new Guid("e592ac73-dfe9-4c32-9404-60526a0e8f5d"),
                            Name = "خرید"
                        });
                });

            modelBuilder.Entity("SabalanTracking.Models.ProductCat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProductCats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("868ecb86-545f-413c-91b4-e15a73f99ddc"),
                            Category = "RawMaterial"
                        },
                        new
                        {
                            Id = new Guid("5efae653-911d-40c9-aaa5-666135fe4a85"),
                            Category = "FinalProduct"
                        },
                        new
                        {
                            Id = new Guid("b234824c-9ddd-4ab1-8626-3f5fa259a4d1"),
                            Category = "Semi Final Prodct"
                        });
                });

            modelBuilder.Entity("SabalanTracking.Models.Material", b =>
                {
                    b.HasOne("SabalanTracking.Models.ProductCat", "ProductCat")
                        .WithMany("Materials")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCat");
                });

            modelBuilder.Entity("SabalanTracking.Models.Proces", b =>
                {
                    b.HasOne("SabalanTracking.Models.Device", "Device")
                        .WithMany("Processs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabalanTracking.Models.Material", "Material")
                        .WithMany("Processs")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabalanTracking.Models.Person", "Person")
                        .WithMany("Processs")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SabalanTracking.Models.ProcessName", "ProcessName")
                        .WithMany()
                        .HasForeignKey("ProcessNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Material");

                    b.Navigation("Person");

                    b.Navigation("ProcessName");
                });

            modelBuilder.Entity("SabalanTracking.Models.ProcessDetaile", b =>
                {
                    b.HasOne("SabalanTracking.Models.Proces", "Proces")
                        .WithMany("ProcessDetails")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proces");
                });

            modelBuilder.Entity("SabalanTracking.Models.Device", b =>
                {
                    b.Navigation("Processs");
                });

            modelBuilder.Entity("SabalanTracking.Models.Material", b =>
                {
                    b.Navigation("Processs");
                });

            modelBuilder.Entity("SabalanTracking.Models.Person", b =>
                {
                    b.Navigation("Processs");
                });

            modelBuilder.Entity("SabalanTracking.Models.Proces", b =>
                {
                    b.Navigation("ProcessDetails");
                });

            modelBuilder.Entity("SabalanTracking.Models.ProductCat", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
